export interface Venue {
  venue_id: string;
  name: string;
  category: string;
  subcategory: string;
  address: string;
  neighborhood: string;
  city: 'Durham' | 'Raleigh';
  avg_cost_pp: number;
  tags: [string, string, string];
  vibe_tags: string[];
  best_for: string[];
  hours_weekday: string;
  hours_weekend: string;
  rating: number;
  dietary_options: string[];
  reservation_needed: boolean;
  group_size_min: number;
  group_size_max: number;
  lat: number;
  lng: number;
  image: string;
  scores: { budget: number; social: number; romantic: number; adventure: number; chill: number; };
}

export const VENUES: Venue[] = [
  // ── Durham Coffee ──
  { venue_id:'V001', name:'Cocoa Cinnamon', category:'coffee', subcategory:'specialty cafe', address:'420 W Geer St', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:12, tags:['Specialty Coffee','Artsy','Cozy'], vibe_tags:['cozy','artsy','indie'], best_for:['date','solo','small group'], hours_weekday:'7am–8pm', hours_weekend:'8am–9pm', rating:4.7, dietary_options:['vegan-friendly','gluten-free options'], reservation_needed:false, group_size_min:1, group_size_max:6, lat:36.0115, lng:-78.9077, image:'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80', scores:{budget:8,social:6,romantic:9,adventure:4,chill:9} },
  { venue_id:'V002', name:'Perennial', category:'coffee', subcategory:'cafe + workspace', address:'621 Foster St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:14, tags:['Work-Friendly','Modern','Light Bites'], vibe_tags:['modern','bright','airy'], best_for:['solo','work','casual date'], hours_weekday:'7am–6pm', hours_weekend:'8am–6pm', rating:4.5, dietary_options:['vegan options','gluten-free options'], reservation_needed:false, group_size_min:1, group_size_max:8, lat:36.0023, lng:-78.9001, image:'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=800&q=80', scores:{budget:7,social:5,romantic:7,adventure:3,chill:8} },
  { venue_id:'V003', name:'Epilogue Books & Coffee', category:'coffee', subcategory:'bookshop cafe', address:'713 N Mangum St', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:11, tags:['Books','Quiet','Indie Vibes'], vibe_tags:['bookish','quiet','cozy'], best_for:['solo','date','small group'], hours_weekday:'8am–7pm', hours_weekend:'9am–7pm', rating:4.8, dietary_options:['vegan options'], reservation_needed:false, group_size_min:1, group_size_max:5, lat:36.0109, lng:-78.9022, image:'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&q=80', scores:{budget:8,social:5,romantic:10,adventure:3,chill:10} },
  { venue_id:'V004', name:'Scratch Bakery', category:'coffee', subcategory:'bakery + brunch', address:'111 Orange St', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:16, tags:['Brunch','Baked Goods','Neighborhood Gem'], vibe_tags:['cozy','homey','popular'], best_for:['brunch','casual date','friends'], hours_weekday:'7am–2pm', hours_weekend:'8am–2pm', rating:4.8, dietary_options:['vegetarian options','vegan options'], reservation_needed:false, group_size_min:1, group_size_max:15, lat:36.0103, lng:-78.9028, image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80', scores:{budget:8,social:7,romantic:7,adventure:4,chill:8} },
  // ── Durham Restaurants ──
  { venue_id:'V005', name:"Zweli's", category:'restaurant', subcategory:'zimbabwean', address:'210 W Parrish St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:28, tags:['African Cuisine','Cultural','Date Night'], vibe_tags:['vibrant','cultural','rich'], best_for:['date','group','special occasion'], hours_weekday:'11am–9pm', hours_weekend:'11am–10pm', rating:4.8, dietary_options:['vegetarian options','gluten-free options'], reservation_needed:true, group_size_min:2, group_size_max:20, lat:36.0011, lng:-78.8991, image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80', scores:{budget:5,social:8,romantic:9,adventure:6,chill:5} },
  { venue_id:'V006', name:'Saltbox Seafood Joint', category:'restaurant', subcategory:'seafood', address:'608 N Mangum St', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:18, tags:['Seafood','Local Favorite','Casual'], vibe_tags:['casual','local','popular'], best_for:['group','casual date','takeout'], hours_weekday:'11am–8pm', hours_weekend:'11am–9pm', rating:4.7, dietary_options:['gluten-free options'], reservation_needed:false, group_size_min:1, group_size_max:15, lat:36.0098, lng:-78.9018, image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&q=80', scores:{budget:7,social:8,romantic:6,adventure:5,chill:7} },
  { venue_id:'V007', name:'Mateo Bar de Tapas', category:'restaurant', subcategory:'spanish tapas', address:'109 W Chapel Hill St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:35, tags:['Tapas','Romantic','Craft Cocktails'], vibe_tags:['upscale','romantic','lively'], best_for:['date','special occasion','group'], hours_weekday:'5pm–10pm', hours_weekend:'5pm–11pm', rating:4.7, dietary_options:['vegetarian options','gluten-free options'], reservation_needed:true, group_size_min:2, group_size_max:12, lat:36.0026, lng:-78.9006, image:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80', scores:{budget:3,social:7,romantic:10,adventure:4,chill:5} },
  { venue_id:'V008', name:'Gocciolone', category:'restaurant', subcategory:'italian', address:'501 Washington St', neighborhood:'Warehouse District', city:'Durham', avg_cost_pp:30, tags:['Italian','Intimate','BYOB'], vibe_tags:['intimate','romantic','rustic'], best_for:['date','special occasion'], hours_weekday:'5pm–10pm', hours_weekend:'5pm–10:30pm', rating:4.9, dietary_options:['vegetarian options','vegan options'], reservation_needed:true, group_size_min:2, group_size_max:10, lat:35.9978, lng:-78.9037, image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80', scores:{budget:4,social:6,romantic:10,adventure:4,chill:6} },
  { venue_id:'V009', name:'Guasaca', category:'restaurant', subcategory:'venezuelan fast casual', address:'318 Blackwell St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:14, tags:['Venezuelan','Fast Casual','Budget-Friendly'], vibe_tags:['casual','quick','flavorful'], best_for:['group','casual','hangout'], hours_weekday:'10am–10pm', hours_weekend:'10am–11pm', rating:4.5, dietary_options:['vegan options','vegetarian options'], reservation_needed:false, group_size_min:1, group_size_max:20, lat:36.0021, lng:-78.9000, image:'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80', scores:{budget:9,social:9,romantic:5,adventure:6,chill:7} },
  { venue_id:'V010', name:'Luna Rotisserie', category:'restaurant', subcategory:'latin american', address:'401 Foster St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:22, tags:['Latin','Rotisserie','Lively Atmosphere'], vibe_tags:['lively','flavorful','warm'], best_for:['date','group','family'], hours_weekday:'11am–10pm', hours_weekend:'11am–11pm', rating:4.6, dietary_options:['gluten-free options','vegetarian options'], reservation_needed:true, group_size_min:2, group_size_max:20, lat:36.0019, lng:-78.9010, image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80', scores:{budget:6,social:8,romantic:8,adventure:5,chill:6} },
  { venue_id:'V011', name:'Dashi', category:'restaurant', subcategory:'japanese / ramen', address:'415 W Teer Rd', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:22, tags:['Ramen','Japanese','Hip Spot'], vibe_tags:['hip','warm','noodle bar'], best_for:['date','casual','solo'], hours_weekday:'11am–10pm', hours_weekend:'11am–11pm', rating:4.6, dietary_options:['vegetarian options','vegan options'], reservation_needed:false, group_size_min:1, group_size_max:12, lat:36.0112, lng:-78.9050, image:'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&q=80', scores:{budget:6,social:7,romantic:7,adventure:5,chill:7} },
  { venue_id:'V012', name:'Pompieri Pizza', category:'restaurant', subcategory:'pizza', address:'190 E Main St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:20, tags:['Pizza','Group-Friendly','Casual'], vibe_tags:['casual','fun','shareable'], best_for:['group','casual date','family'], hours_weekday:'11am–10pm', hours_weekend:'11am–11pm', rating:4.5, dietary_options:['vegan options','gluten-free crust'], reservation_needed:false, group_size_min:2, group_size_max:25, lat:36.0035, lng:-78.8985, image:'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&q=80', scores:{budget:7,social:9,romantic:6,adventure:5,chill:7} },
  // ── Durham Bars ──
  { venue_id:'V013', name:'Motorco Music Hall', category:'bar', subcategory:'live music venue', address:'723 Rigsbee Ave', neighborhood:'Warehouse District', city:'Durham', avg_cost_pp:15, tags:['Live Music','Indie','Late Night'], vibe_tags:['indie','loud','energetic'], best_for:['group','concert night','nightlife'], hours_weekday:'4pm–2am', hours_weekend:'4pm–2am', rating:4.5, dietary_options:['bar snacks','vegan options'], reservation_needed:false, group_size_min:4, group_size_max:200, lat:35.9983, lng:-78.9038, image:'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80', scores:{budget:7,social:10,romantic:5,adventure:8,chill:4} },
  { venue_id:'V014', name:'Fullsteam Brewery', category:'bar', subcategory:'craft brewery', address:'726 Rigsbee Ave', neighborhood:'Warehouse District', city:'Durham', avg_cost_pp:16, tags:['Craft Beer','Dog-Friendly','Communal Tables'], vibe_tags:['communal','local','laid-back'], best_for:['group','casual','date'], hours_weekday:'4pm–12am', hours_weekend:'2pm–2am', rating:4.6, dietary_options:['vegetarian snacks','vegan options'], reservation_needed:false, group_size_min:2, group_size_max:50, lat:35.9985, lng:-78.9037, image:'https://images.unsplash.com/photo-1436076863939-06870fe779c2?w=800&q=80', scores:{budget:8,social:10,romantic:5,adventure:6,chill:7} },
  { venue_id:'V015', name:'Federal Bar & Lounge', category:'bar', subcategory:'cocktail lounge', address:'914 N Mangum St', neighborhood:'Old North Durham', city:'Durham', avg_cost_pp:18, tags:['Craft Cocktails','Intimate','Neighborhood Bar'], vibe_tags:['intimate','craft cocktails','chill'], best_for:['date','small group','nightcap'], hours_weekday:'5pm–1am', hours_weekend:'5pm–2am', rating:4.5, dietary_options:['snacks'], reservation_needed:false, group_size_min:2, group_size_max:12, lat:36.0122, lng:-78.9020, image:'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80', scores:{budget:6,social:7,romantic:8,adventure:5,chill:7} },
  { venue_id:'V016', name:'Durham Hotel Rooftop', category:'bar', subcategory:'rooftop bar', address:'315 E Chapel Hill St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:20, tags:['Rooftop','City Views','Trendy'], vibe_tags:['upscale','views','trendy'], best_for:['date','small group','special occasion'], hours_weekday:'4pm–12am', hours_weekend:'12pm–12am', rating:4.6, dietary_options:['snacks','small plates'], reservation_needed:false, group_size_min:2, group_size_max:30, lat:36.0024, lng:-78.8975, image:'https://images.unsplash.com/photo-1547235001-d703406d3f17?w=800&q=80', scores:{budget:5,social:7,romantic:9,adventure:5,chill:6} },
  { venue_id:'V017', name:'The Pinhook', category:'bar', subcategory:'dive bar + venue', address:'117 W Main St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:12, tags:['Dive Bar','Local Music','No Frills'], vibe_tags:['gritty','artsy','dive'], best_for:['group','concert','nightlife'], hours_weekday:'5pm–2am', hours_weekend:'5pm–2am', rating:4.4, dietary_options:['bar snacks'], reservation_needed:false, group_size_min:3, group_size_max:100, lat:36.0033, lng:-78.9011, image:'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80', scores:{budget:9,social:10,romantic:4,adventure:7,chill:5} },
  // ── Durham Activities ──
  { venue_id:'V018', name:'Bull City Escape', category:'activity', subcategory:'escape room', address:'107 E Parrish St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:28, tags:['Escape Room','Team Activity','Date-Worthy'], vibe_tags:['fun','teamwork','intense'], best_for:['group','date','team outing'], hours_weekday:'By appt', hours_weekend:'By appt', rating:4.6, dietary_options:[], reservation_needed:true, group_size_min:2, group_size_max:8, lat:36.0017, lng:-78.8990, image:'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&q=80', scores:{budget:6,social:9,romantic:7,adventure:9,chill:5} },
  { venue_id:'V019', name:'Alley Twenty Six', category:'activity', subcategory:'bowling + cocktails', address:'120 E Parrish St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:30, tags:['Bowling','Retro Vibes','Cocktails'], vibe_tags:['retro','fun','social'], best_for:['group','date','birthday'], hours_weekday:'4pm–12am', hours_weekend:'2pm–2am', rating:4.5, dietary_options:['small bites','vegan options'], reservation_needed:true, group_size_min:2, group_size_max:16, lat:36.0016, lng:-78.8989, image:'https://images.unsplash.com/photo-1544919982-b61976f0ba43?w=800&q=80', scores:{budget:6,social:9,romantic:7,adventure:7,chill:6} },
  { venue_id:'V020', name:'Triangle Rock Club', category:'activity', subcategory:'rock climbing', address:'3204 Hillsborough Rd', neighborhood:'West Durham', city:'Durham', avg_cost_pp:22, tags:['Rock Climbing','Active','Community Gym'], vibe_tags:['active','social','challenging'], best_for:['group','date','adventure'], hours_weekday:'12pm–10pm', hours_weekend:'10am–8pm', rating:4.7, dietary_options:[], reservation_needed:false, group_size_min:2, group_size_max:20, lat:36.0089, lng:-78.9512, image:'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800&q=80', scores:{budget:7,social:7,romantic:6,adventure:10,chill:4} },
  { venue_id:'V021', name:'Durham Bulls Athletic Park', category:'activity', subcategory:'baseball', address:'409 Blackwell St', neighborhood:'Downtown Durham', city:'Durham', avg_cost_pp:18, tags:['Baseball','Classic Americana','Group Outing'], vibe_tags:['sporty','lively','classic'], best_for:['group','casual','families'], hours_weekday:'Game days', hours_weekend:'Game days', rating:4.8, dietary_options:['concessions','vegan options'], reservation_needed:false, group_size_min:2, group_size_max:999, lat:35.9976, lng:-78.9008, image:'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&q=80', scores:{budget:8,social:10,romantic:5,adventure:8,chill:6} },
  // ── Durham Outdoor ──
  { venue_id:'V022', name:'Durham Central Park', category:'outdoor', subcategory:'park', address:'501 Foster St', neighborhood:'Central Durham', city:'Durham', avg_cost_pp:0, tags:['Free','Picnic Spot','Dog-Friendly'], vibe_tags:['chill','open','free'], best_for:['group','date','picnic'], hours_weekday:'Always open', hours_weekend:'Always open', rating:4.5, dietary_options:[], reservation_needed:false, group_size_min:1, group_size_max:100, lat:36.0027, lng:-78.9037, image:'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80', scores:{budget:10,social:8,romantic:7,adventure:7,chill:10} },
  { venue_id:'V023', name:'Eno River State Park', category:'outdoor', subcategory:'hiking / nature', address:'Cole Mill Rd', neighborhood:'North Durham', city:'Durham', avg_cost_pp:0, tags:['Hiking','Swimming Holes','Nature'], vibe_tags:['serene','outdoor','nature'], best_for:['date','solo','group'], hours_weekday:'6am–9pm', hours_weekend:'6am–9pm', rating:4.9, dietary_options:[], reservation_needed:false, group_size_min:1, group_size_max:50, lat:36.0756, lng:-79.0018, image:'https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80', scores:{budget:10,social:6,romantic:8,adventure:10,chill:7} },
  // ── Raleigh Coffee ──
  { venue_id:'V024', name:'Jubala Coffee', category:'coffee', subcategory:'specialty cafe', address:'1200 Tryon Village Dr', neighborhood:'North Hills', city:'Raleigh', avg_cost_pp:13, tags:['Specialty Coffee','Minimalist','Quiet'], vibe_tags:['minimal','focused','quality'], best_for:['solo','work','date'], hours_weekday:'7am–6pm', hours_weekend:'8am–6pm', rating:4.8, dietary_options:['vegan options','gluten-free options'], reservation_needed:false, group_size_min:1, group_size_max:8, lat:35.8526, lng:-78.6382, image:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80', scores:{budget:7,social:5,romantic:8,adventure:3,chill:9} },
  { venue_id:'V025', name:'Videri Chocolate Factory', category:'coffee', subcategory:'chocolate + cafe', address:'327 W Davie St', neighborhood:'Warehouse District', city:'Raleigh', avg_cost_pp:14, tags:['Bean-to-Bar','Unique Date','Artisan'], vibe_tags:['unique','sweet','artisan'], best_for:['date','special treat','foodie'], hours_weekday:'9am–6pm', hours_weekend:'10am–6pm', rating:4.8, dietary_options:['vegan options','gluten-free options'], reservation_needed:false, group_size_min:1, group_size_max:15, lat:35.7793, lng:-78.6511, image:'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&q=80', scores:{budget:7,social:6,romantic:9,adventure:4,chill:8} },
  // ── Raleigh Restaurants ──
  { venue_id:'V026', name:'Bida Manda', category:'restaurant', subcategory:'laotian', address:'222 S Blount St', neighborhood:'Downtown Raleigh', city:'Raleigh', avg_cost_pp:30, tags:['Laotian','James Beard','Date Night'], vibe_tags:['upscale','unique','romantic'], best_for:['date','special occasion','foodie'], hours_weekday:'5pm–10pm', hours_weekend:'5pm–11pm', rating:4.8, dietary_options:['vegetarian options','gluten-free options'], reservation_needed:true, group_size_min:2, group_size_max:20, lat:35.7741, lng:-78.6335, image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&q=80', scores:{budget:4,social:7,romantic:10,adventure:7,chill:5} },
  { venue_id:'V027', name:'Brewery Bhavana', category:'bar', subcategory:'brewery + dim sum', address:'218 S Blount St', neighborhood:'Downtown Raleigh', city:'Raleigh', avg_cost_pp:28, tags:['Dim Sum','Craft Beer','Flower Shop'], vibe_tags:['unique','artsy','instagram-worthy'], best_for:['date','group','brunch'], hours_weekday:'11am–10pm', hours_weekend:'10am–11pm', rating:4.7, dietary_options:['vegetarian options','vegan options'], reservation_needed:true, group_size_min:2, group_size_max:30, lat:35.7743, lng:-78.6337, image:'https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&q=80', scores:{budget:5,social:8,romantic:9,adventure:6,chill:6} },
  { venue_id:'V028', name:'Trophy Brewing Company', category:'bar', subcategory:'brewery + pizza', address:'827 W Morgan St', neighborhood:'Boylan Heights', city:'Raleigh', avg_cost_pp:20, tags:['Craft Beer','Wood-Fired Pizza','Patio'], vibe_tags:['laid-back','local','outdoor patio'], best_for:['group','casual','date'], hours_weekday:'3pm–10pm', hours_weekend:'12pm–11pm', rating:4.7, dietary_options:['vegetarian options','vegan options'], reservation_needed:false, group_size_min:2, group_size_max:40, lat:35.7768, lng:-78.6571, image:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80', scores:{budget:7,social:9,romantic:6,adventure:5,chill:8} },
  { venue_id:'V029', name:'Foundation Bar', category:'bar', subcategory:'underground bar', address:'213 Fayetteville St', neighborhood:'Downtown Raleigh', city:'Raleigh', avg_cost_pp:15, tags:['Underground','Moody Vibes','Cocktails'], vibe_tags:['underground','moody','cool'], best_for:['date','nightlife','group'], hours_weekday:'5pm–2am', hours_weekend:'5pm–2am', rating:4.4, dietary_options:['bar snacks'], reservation_needed:false, group_size_min:2, group_size_max:80, lat:35.7783, lng:-78.6381, image:'https://images.unsplash.com/photo-1575444758702-4a6b9222336e?w=800&q=80', scores:{budget:7,social:8,romantic:7,adventure:7,chill:6} },
  // ── Raleigh Outdoor ──
  { venue_id:'V030', name:'Pullen Park', category:'outdoor', subcategory:'park + carousel', address:'520 Ashe Ave', neighborhood:'Pullen', city:'Raleigh', avg_cost_pp:3, tags:['Historic Park','Carousel','Paddleboats'], vibe_tags:['nostalgic','fun','outdoors'], best_for:['group','date','families'], hours_weekday:'7am–9pm', hours_weekend:'7am–9pm', rating:4.7, dietary_options:['concessions'], reservation_needed:false, group_size_min:1, group_size_max:50, lat:35.7832, lng:-78.6714, image:'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80', scores:{budget:10,social:8,romantic:7,adventure:6,chill:8} },
];
